### PR TITLE
Fix: use correct intent when calling registerLastBiometrics

### PR DESCRIPTION
**Pull request by tsuharesu**

### CODE REVIEW

**Comment by ethiery** [comment]
Could you refresh my memory on what happened there? I'll take a stab at it, and you can tell me if I am wrong. It looks like:
- First, we added in Simprints ID the capability to enroll a subject using the biometrics captured in a previous session, when receiving a `REGISTER` intent that contained a `sessionId` extra . I guess that was the very first iteration of "ID before enroll"
- Then, we added support in Simprints ID for a separate intent for that (`REGISTER_LAST_BIOMETRICS`), but did not update SimHelper yet. Was that a breaking change, or did we continue supporting the `REGISTER` intent with `sessionId` extra?
- Now you are upgrading SimHelper to use the second option

**Comment by tsuharesu** [comment]
@ethiery I didn't know SID supported `REGISTER` with `sessionId` before. I don't think so because users are having problem with it.

But yes for the end of it. SID only supports `REGISTER_LAST_BIOMETRICS` now.

**Comment by ethiery** [comment]
Well, I don't actually know for sure that it did support it, but I am having a hard time imagining Fabio could make such a big oversight as to use the wrong intent [when he added `registerLastBiometrics`](https://github.com/Simprints/LibSimprints/commit/f90213bd1fd6447605ce97c4f4ceebac951325e0#diff-f6d810dbac0f9eeed86fc3c2a395cab1240dea6166d14c715200debf34d40a41) for 2020.3.0

**Comment by ethiery** [comment]
Anyways, I gave a quick look at the intent parsing within Simprints ID, and what you did looks good to me. So, for what it's worth you got my thumbs up.

**Review by ethiery — APPROVED** [review]

**Comment by TristramN** [comment]
@tsuharesu it looks like there is also a bug with this where we can't call `REGISTER_LAST_BIOMETRICS` without `metadata` currently? All the other calls support not adding metadata. Do you know if this is intended? If not then I believe this is a bug and could you please add the none metadata call? Thanks!

**Comment by tsuharesu** [comment]
@TristramN let me check on SID side and I can update this with `Nullable` Metadata.

**Comment by TristramN** [comment]
Cool! Another option is to duplicate the [current pattern](https://github.com/Simprints/LibSimprints/blob/master/src/main/java/com/simprints/libsimprints/SimHelper.java#L100-L129). Might be more readable for people who look at it in the future IMO.

**Review by TristramN — APPROVED** [review]

**Pull request merged**
