### PR TITLE
Include gradle wrapper

### LINKED ISSUE #11: Gradle wrapper's `gradle` directory is missing
Checking out the project and running gradle wrapper gives the following error:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

It appears that the `gradle` directory normally included with `gradlew` has not been committed.

As per gradle docs at https://docs.gradle.org/current/userguide/gradle_wrapper.html:

> Example 5.3. Wrapper generated files
>
> Build layout
> ```
>    simple/
>      gradlew
>      gradlew.bat
>      gradle/wrapper/
>        gradle-wrapper.jar
>        gradle-wrapper.properties
>```
>  All of these files should be submitted to your version control system.

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #11

I don't know what version of gradle wrapper is actually being used by the project, so I picked the latest (3.5).  From the changes to `gradlew`, it looks like I picked wrong.

### CODE REVIEW

**Comment by ghost** [comment]
I've included the `gradle-wrapper.properties` file in the `includeGradleProperties` branch. Does this solve your issue?

Ridwan

**Comment by alxndrsn** [comment]
No, this doesn't solve it:

```
$ git clone git@github.com:SimPrints/LibSimprints.git && cd LibSimprints && git checkout includeGradleWrapper && ./gradlew tasks
Cloning into 'LibSimprints'...
remote: Counting objects: 528, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 528 (delta 1), reused 3 (delta 0), pack-reused 517
Receiving objects: 100% (528/528), 137.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (183/183), done.
Branch includeGradleWrapper set up to track remote branch includeGradleWrapper from origin.
Switched to a new branch 'includeGradleWrapper'
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

From [gradle documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:wrapper_generation):

>
>```
>  gradlew
>  gradlew.bat
>  gradle/wrapper/
>    gradle-wrapper.jar
>    gradle-wrapper.properties
>```
> All of these files _should_ be submitted to your version control system.

**Comment by ghost** [comment]
All the files:
>  gradlew
>  gradlew.bat
>  gradle/wrapper/gradle-wrapper.jar
>  gradle/wrapper/gradle-wrapper.properties

Should be on that branch now.

Ridwan

**Comment by alxndrsn** [comment]
👍

**Pull request closed without merging**
